<?php

namespace DesoukOnline\ArticleBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ArticleHasCategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticleHasCategoryRepository extends EntityRepository
{
    /**
     * @ORM\Id
     * @ORM\Column(type="integer")
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    protected $id;

    /**
     *  @ORM\ManyToOne(targetEntity="Article", inversedBy="article_category", cascade={"all"})
     */
    protected $idArticle;

    /**
     * @param \Doctrine\ORM\Mapping\ClassMetadata $class
     */
    public function setClass($class)
    {
        $this->_class = $class;
    }

    /**
     * @return \Doctrine\ORM\Mapping\ClassMetadata
     */
    public function getClass()
    {
        return $this->_class;
    }

    /**
     * @param \Doctrine\ORM\EntityManager $em
     */
    public function setEm($em)
    {
        $this->_em = $em;
    }

    /**
     * @return \Doctrine\ORM\EntityManager
     */
    public function getEm()
    {
        return $this->_em;
    }

    /**
     * @param mixed $id
     */
    public function setId($id)
    {
        $this->id = $id;
    }

    /**
     * @return mixed
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * @param mixed $id_article
     */
    public function setIdArticle($idArticle)
    {
        $this->idArticle = $idArticle;
    }

    /**
     * @return mixed
     */
    public function getIdArticle()
    {
        return $this->idArticle;
    }

    /**
     * @param mixed $id_category
     */
    public function setIdCategory($idCategory)
    {
        $this->idCategory = $idCategory;
    }

    /**
     * @return mixed
     */
    public function getIdCategory()
    {
        return $this->idCategory;
    }

    /**
     *  @ORM\ManyToOne(targetEntity="Category", inversedBy="category_article", cascade={"all"})
     */
    private $idCategory;

    public function __construct() {

    }
}
