<?php

namespace DesoukOnline\ArticleBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ArticleTranslationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticleTranslationRepository extends EntityRepository
{
}
