<?php

namespace DesoukOnline\BannerBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * BannerTranslationsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BannerTranslationsRepository extends EntityRepository
{
}
