services:
    desouk_online.news:
        class: DesoukOnline\NewsBundle\Admin\NewsAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "DesoukOnline", label: "News" }
        arguments:
            - ~
            - DesoukOnline\NewsBundle\Entity\News
            - ~
        calls:
            - [ setTranslationDomain, [DesoukOnlineNewsBundle]]