services:
    desouk_online.car:
        class: DesoukOnline\CarBundle\Admin\CarAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "DesoukOnline", label: "Car" , show_in_dashboard: true }
        arguments:
            - ~
            - DesoukOnline\CarBundle\Entity\Car
            - ~