services:
    desouk_online.faq:
        class: DesoukOnline\FaqBundle\Admin\FaqAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "DesoukOnline", label: "Faqs" }
        arguments:
            - ~
            - DesoukOnline\FaqBundle\Entity\Faq
            - ~
        calls:
            - [ setTranslationDomain, [DesoukOnlineFaqBundle]]