services:
    desouk_online.focus:
        class: DesoukOnline\FocusBundle\Admin\FocusAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "DesoukOnline", label: "Focus" }
        arguments:
            - ~
            - DesoukOnline\FocusBundle\Entity\Focus
            - ~
        calls:
            - [ setTranslationDomain, [DesoukOnlineFocusBundle]]