services:
    desouk_online.category:
        class: DesoukOnline\ProductBundle\Admin\CategoryAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "DesoukOnline", label: "Product Category" }
        arguments:
            - ~
            - DesoukOnline\ProductBundle\Entity\Category
            - ~
        calls:
            - [ setTranslationDomain, [DesoukOnlineProductBundle]]