services:
    desouk_online.product:
        class: DesoukOnline\ProductBundle\Admin\ProductAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "DesoukOnline", label: "Product" }
        arguments:
            - ~
            - DesoukOnline\ProductBundle\Entity\Product
            - ~
        calls:
            - [ setTranslationDomain, [DesoukOnlineProductBundle]]