services:
    desouk_online.producthastag:
        class: DesoukOnline\ProductBundle\Admin\ProductHasTagAdmin
        tags:
            - { name: sonata.admin, manager_type: orm }
        arguments:
            - ~
            - DesoukOnline\ProductBundle\Entity\ProductHasTag
            - ~
        calls:
            - [ setTranslationDomain, [DesoukOnlineProductBundle]]