services:
    desouk_online.producthascategory:
        class: DesoukOnline\ProductBundle\Admin\ProductHasCategoryAdmin
        tags:
            - { name: sonata.admin, manager_type: orm }
        arguments:
            - ~
            - DesoukOnline\ProductBundle\Entity\ProductHasCategory
            - ~
        calls:
            - [ setTranslationDomain, [DesoukOnlineProductBundle]]