services:
    desouk_online.articlecategory:
        class: DesoukOnline\ArticleBundle\Admin\CategoryAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "DesoukOnline", label: "Article category" , show_in_dashboard: true }
        arguments:
            - ~
            - DesoukOnline\ArticleBundle\Entity\Category
            - ~
