services:
    desouk_online.article:
        class: DesoukOnline\ArticleBundle\Admin\ArticleAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "DesoukOnline", label: "Article" , show_in_dashboard: true }
        arguments:
            - ~
            - DesoukOnline\ArticleBundle\Entity\Article
            - ~