services:
    desouk_online.for_sale:
        class: DesoukOnline\ForSaleBundle\Admin\ForSaleAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "DesoukOnline", label: "For Sale" , show_in_dashboard: true }
        arguments:
            - ~
            - DesoukOnline\ForSaleBundle\Entity\ForSale
            - ~

    desouk_online.for_sale_category:
        class: DesoukOnline\ForSaleBundle\Admin\ForSaleCategoryAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "DesoukOnline", label: "For Sale Category" , show_in_dashboard: true }
        arguments:
            - ~
            - DesoukOnline\ForSaleBundle\Entity\Category
            - ~

    desouk_online.for_sale.image:
        class: DesoukOnline\ForSaleBundle\Admin\ImageAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "DesoukOnline", label: "Images" , show_in_dashboard: true }
        arguments:
            - ~
            - DesoukOnline\ForSaleBundle\Entity\Image
            - ~