services:
    desouk_online.jobs.config:
        class: DesoukOnline\JobsBundle\Admin\JobsConfigAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "DesoukOnline", label: "Jobs Config" , show_in_dashboard: true }
        arguments:
            - ~
            - DesoukOnline\JobsBundle\Entity\JobsConfig
            - ~

    desouk_online.jobs:
        class: DesoukOnline\JobsBundle\Admin\JobsAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "DesoukOnline", label: "Jobs" , show_in_dashboard: true }
        arguments:
            - ~
            - DesoukOnline\JobsBundle\Entity\Job
            - ~